import type {Metadata} from 'next'
import {Inter} from 'next/font/google'
import './globals.css'
import Link from "next/link";

const inter = Inter({subsets: ['latin']})

export const metadata: Metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app',
}

export default function RootLayout({
                                       children,
                                   }: {
    children: React.ReactNode
}) {
    return (
        <html lang="en">
        <body className={inter.className}>
        <header>
            <nav className="flex justify-between px-32">
                <h2 className="text-3xl font-bold">My Blog</h2>
                <ul className="flex gap-4 text-xl">
                    <li><Link href="/">home</Link></li>
                    <li><Link href="/about">about</Link></li>
                    <li><Link href="/posts">posts</Link></li>
                    <li><Link href="/contact">contact</Link></li>
                </ul>
            </nav>
        </header>
        {children}
        </body>
        </html>
    )
}
